server.port=8082

spring.application.name=order-service

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# gRPC server
grpc.server.port=9082

# gRPC clients
grpc.client.payment-service.address=static://localhost:9081
grpc.client.payment-service.negotiation-type=plaintext
grpc.client.inventory-service.address=static://localhost:9083
grpc.client.inventory-service.negotiation-type=plaintext
grpc.client.saga-orchestrator.address=static://localhost:9084
grpc.client.saga-orchestrator.negotiation-type=plaintext

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.saga.order=DEBUG
logging.level.org.springframework.kafka=INFO

# Outbox poller
outbox.poller.fixed-delay-ms=2000
outbox.poller.batch-size=50
outbox.poller.send-timeout-ms=5000
